### PR TITLE
Fix/misc

### LINKED ISSUE #110: mplex header read incorrectly
https://github.com/status-im/nim-libp2p/blob/b1a34f478efe6d1212cfccecaf4dd8bf89fc2b1f/libp2p/muxers/mplex/coder.nim#L52

reading the header calls `readMplexVarint` which raises when the varint is bigger than max message size,  this however is not applicable for the header itself

https://github.com/status-im/nim-libp2p/blob/b1a34f478efe6d1212cfccecaf4dd8bf89fc2b1f/libp2p/muxers/mplex/coder.nim#L64

converting to `MessageType` is not safe - 7 is not a valid value for the enum

### PR DESCRIPTION
**Pull request by dryajov**
Fixes #110, #109.

### CODE REVIEW

File: libp2p/muxers/mplex/coder.nim [hunk 1]
```diff
@@ -55,6 +53,9 @@ proc readMsg*(conn: Connection): Future[Msg] {.async, gcsafe.} =
   let dataLenVarint = await conn.readMplexVarint()
   trace "read data len varint", varint = dataLenVarint
 
+  if dataLenVarint.int > DefaultReadSize:
+    raise newInvalidVarintSizeException()
```
Comment (arnetheduck) [inline libp2p/muxers/mplex/coder.nim]: technically it's not the varint that is wrong ;)
