### PR TITLE
fix varint issues

### LINKED ISSUE #111: Unsafe usage of `uint`
`uint` is a system-sized type, yet we're using it in cross-network situations, like here - this should use a specifically sized type throughout:

https://github.com/status-im/nim-libp2p/blob/b1a34f478efe6d1212cfccecaf4dd8bf89fc2b1f/libp2p/muxers/mplex/coder.nim#L25

### PR DESCRIPTION
**Pull request by arnetheduck**
* fixes #111
* fixes remote varint size exploit in identify

### CODE REVIEW

**Comment by arnetheduck** [comment]
varint fixes from #118

File: libp2p/stream/lpstream.nim [hunk 1]
```diff
@@ -109,6 +114,45 @@ proc readLine*(s: LPStream, limit = 0, sep = "\r\n"): Future[string] {.async, de
...
+    await conn.readExactly(addr buffer[i], 1)
+    let res = PB.getUVarint(buffer.toOpenArray(0, i), length, varint)
+    if res == VarintStatus.Success:
+      return varint
+    if res != VarintStatus.Incomplete:
+      break
+  if true: # can't end with a raise apparently
+    raise (ref InvalidVarintError)(msg: "Cannot parse varint")
+
+proc readLp*(s: LPStream, maxSize: int): Future[seq[byte]] {.async, gcsafe.} =
```
Comment (dryajov) [inline libp2p/stream/lpstream.nim:133]: Not sure about this, it still doesn't make sense to pass a max size.

Comment (dryajov) [reply libp2p/stream/lpstream.nim:133]: Usually max size is set per protocol, not per read invocation.

Comment (arnetheduck) [reply libp2p/stream/lpstream.nim:133]: protocols have helpers for their own types though where they set this (`mplex.readMsg`) - you'll note that `readExactly`, `read`, etc all take a max size at this abstraction level

Comment (arnetheduck) [reply libp2p/stream/lpstream.nim:133]: potentially, `Connection` could have a helper without the max-len, assuming `Connection` is "heavy enough"

Comment (arnetheduck) [reply libp2p/stream/lpstream.nim:133]: consider also the multiple security problems we've been having with headers / negotiations - ie these typically have smaller max read sizes, so even within a protocol there will be differences

Comment (arnetheduck) [reply libp2p/stream/lpstream.nim:133]: https://github.com/status-im/nim-beacon-chain/blob/master/beacon_chain/eth2_network.nim#L265 - I'd like to use it here fore example with a custom chunk size

Comment (dryajov) [reply libp2p/stream/lpstream.nim:133]: well, now that I think about it, if we move it to lpstream, then it probably is OK to leave it with the max size, and have an overload without the max (or a global max).

Comment (dryajov) [reply libp2p/stream/lpstream.nim:133]: In fact, I'm thinking that the whole lpstream abstraction should go and connection should be the abstract base class that all other streams extend. This will fix all our closing issues which stem from the fact that we have to nest streams multiple times.
