### PR TITLE
Fix finally use in daemonapi

### LINKED ISSUE #39: using `finally` ends connections prematurely in `daemonapi`
Commit dde8c01448e0302c99c39fcd02ced88431a60d27 introduced a bug, whereby using `finally` the connection/transport is closed prematurely. This is because `finally` is triggered **always**, either on exception within the `try` block or when leaving the `try` scope. Using `finally` closes the connection/transport before it gets a chance to be used by the caller. 

It should be changed back to proper exception handling, probably something like:

```nim
try
  ...
except Exception as exc:
  # do cleanup - stop transport, etc...
  # re-raise exception
  raise exc
```

### PR DESCRIPTION
**Pull request by dryajov**
Fixes #39 

Reverting dde8c01448e0302c99c39fcd02ced88431a60d27 to proper exception handling. 

Note that `Exception` instead of `CatchableError` is used to emulate previous behavior of `raise getCurrentException()`.

### CODE REVIEW

**Comment by dryajov** [comment]
The tests are further broken by chronos around commit https://github.com/status-im/nim-chronos/commit/bf393def768cd15ff29238c1f6d2fcaa563a03c4

File: libp2p/protocols/secure/secio.nim [hunk 1]
```diff
@@ -404,8 +404,8 @@ proc readLoop(sconn: SecureConnection, stream: BufferStream) {.async.} =
     try:
       let msg = await sconn.readMessage()
       await stream.pushTo(msg)
-    except CatchableError as exc:
-      trace "exception in secio", exc = exc
+    except Exception as exc:
```
Comment (zah) [inline libp2p/protocols/secure/secio.nim]: While the other cases of handling and re-raising `Exceptions` seem OK to me, recovering from `Defects` here doesn't seem appropriate. I've pushed another commit changing this back to `CatchableError`.
