### PR TITLE
Fix #61.

### LINKED ISSUE #61: Connecting to the daemon from the native implementation using Secp256k1 fails in secio.
When connecting to the go daemon from the native implementation, using the `Secp256k1` curve the daemon fails with a failure in secio, other curves supported by libp2p such as `ECDSA` or `RSA` work fine. 

The Secp256k1 implementation used in libp2p is https://github.com/status-im/nim-secp256k1, which is a wrapper of a fork https://github.com/status-im/secp256k1 of the core bitcoin secp256k1.

The specific failure that's thrown by the daemon is `ERROR      secio: 2.1 Verify: failed: %s malformed signature: no header magic protocol.go:314`. 

Here is a quick script to reproduce it:

```nim
import options
import chronos
import ../libp2p/[standard_setup,
                  daemon/daemonapi,
                  peerinfo,
                  crypto/crypto]

type
  NativePeerInfo = peerinfo.PeerInfo

proc main() {.async.} =
  var protos = @["/test-stream"]

  let nativeNode = newStandardSwitch(privKey = some(PrivateKey.random(PKScheme.Secp256k1)))
  let awaiters = await nativeNode.start()
  let daemonNode = await newDaemonApi()
  let daemonPeer = await daemonNode.identity()

  proc daemonHandler(api: DaemonAPI, stream: P2PStream) {.async.} =
    discard

  await daemonNode.addHandler(protos, daemonHandler)
  discard await nativeNode.dial(NativePeerInfo.init(daemonPeer.peer,
                                                    daemonPeer.addresses),
                                                    protos[0])
  await sleepAsync(1.seconds)

waitFor(main())
```

### PR DESCRIPTION
**Pull request by cheatfate**
@dryajov please check it against other implementations. Source you supplied in issue is working properly.

### CODE REVIEW

File: libp2p/crypto/secp.nim [hunk 1]
```diff
@@ -299,8 +300,9 @@ proc getBytes*(key: SkPublicKey): seq[byte] {.inline.} =
 
 proc getBytes*(sig: SkSignature): seq[byte] {.inline.} =
   ## Serialize Secp256k1 `signature` and return it.
-  result = newSeq[byte](SkRawSignatureSize)
-  discard toBytes(sig, result)
+  result = newSeq[byte](72)
+  let length = toBytes(sig, result)
+  result.setLen(length)
```
Comment (dryajov) [inline libp2p/crypto/secp.nim]: would `length` ever be less than 72 bytes?

Comment (cheatfate) [reply libp2p/crypto/secp.nim]: yep.

Comment (cheatfate) [reply libp2p/crypto/secp.nim]: https://github.com/status-im/secp256k1/blob/be6f5385330905bf1d7cc441be6703cfa7aef847/src/ecdsa_impl.h#L177-L186
