### PR TITLE
fix: use exact types for mplex id

### LINKED ISSUE #111: Unsafe usage of `uint`
`uint` is a system-sized type, yet we're using it in cross-network situations, like here - this should use a specifically sized type throughout:

https://github.com/status-im/nim-libp2p/blob/b1a34f478efe6d1212cfccecaf4dd8bf89fc2b1f/libp2p/muxers/mplex/coder.nim#L25

### PR DESCRIPTION
**Pull request by dryajov**
Fixes #111

### CODE REVIEW

File: libp2p/muxers/mplex/coder.nim [hunk 1]
```diff
@@ -61,10 +61,10 @@ proc readMsg*(conn: Connection): Future[Msg] {.async, gcsafe.} =
     trace "read data", data = data.len
 
   let header = headerVarint
```
Comment (arnetheduck) [inline libp2p/muxers/mplex/coder.nim]: headerVarint is still an `uint` so bigger values are still lost

**Comment by arnetheduck** [comment]
alright, this branch is an improvement already because at least if a big id is received, the implementation is broken the same way on all platforms :)

**Comment by dryajov** [comment]
I'm not sure why compilation is failing, is this some sort of Nim bug @zah @arnetheduck?
